-- Migration: Create leads_clients table
-- Description: Stores client inquiries submitted via the contact form

create table if not exists public.leads_clients (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now() not null,
    legal_name text not null,
    client_email text not null,
    phone_number text not null,
    message text,
    constraint legal_name_check check (char_length(legal_name) <= 100),
    constraint client_email_check check (char_length(client_email) <= 100),
    constraint phone_number_check check (char_length(phone_number) <= 20)
);

-- Enable Row Level Security
alter table public.leads_clients enable row level security;

-- Only allow inserts from the service role API (no public inserts)
create policy "Only service role can insert"
    on public.leads_clients
    for insert
    to service_role
    with check (true);

-- Only service role can select (for admin views)
create policy "Only service role can select"
    on public.leads_clients
    for select
    to service_role
    using (true);

-- Index on created_at for ordering queries
create index if not exists idx_leads_clients_created_at
    on public.leads_clients (created_at desc);
